### ISSUE TITLE
Game Crashes Out on World Generation

### ISSUE THREAD

**Issue by AshrielV** [MoriyaShiine/bewitchment#251]
Using bewitchment 1.18-8
Game crashes as newly generated world is loading in
Took me a long time to isolate that this mod was causing it, I unfortunately do not know what the conflict was. See the crashlog included below.
[crash-2022-02-01_00.37.09-server.txt](https://github.com/MoriyaShiine/bewitchment/files/7976147/crash-2022-02-01_00.37.09-server.txt)

**Comment by MoriyaShiine** [comment]
Not caused by bewitchment, but unfortunately by a library included in bewitchment that I can't do anything about; please report to step height entity attribute or better animals plus

It looks like this would fix it on BAP's end, I'll ask meow https://github.com/emilyploszaj/step-height-entity-attribute/issues/4
