### ISSUE TITLE
[1.18.2 Crash] Bewitchment crops not compatible with Greenhouse (Croparia Mod)

### ISSUE THREAD

**Issue by MSandro** [MoriyaShiine/bewitchment#330]
### Mod version

1.18-23

### A description of the issue

Fabric Loader: 0.14.10
Fabric API: 0.67.0
Bewitchment: 1.18-23
Croparia: 3.8.3
No idea what mod is triggering it, but to me it looks like the Bewitchment crops aren't implemented properly.
https://github.com/Dalarion/Croparia/issues/22

### Log or crash report

https://github.com/MSandro/sky_fabrication3/files/10105243/crash-2022-11-27_19.12.04-server.txt

**Comment by MoriyaShiine** [comment]
This is on Croparia, it assumes all crops that aren't Beetroot have the same age property.
https://github.com/Dalarion/Croparia/blob/master/src/main/java/com/croparia/mod/common/blockEntity/GreenHouseBE.java#L49

Luckily this is fixable on their end by getting the CropBlock's age property (with CropBlock#getAgeProperty() in yarn) instead of *always* the one for wheat and other non-beetroot blocks, and would fix crashes with any other mod that also uses different age properties
