### ISSUE TITLE
Crash when hitting ghost | fabric 1.19.2

### ISSUE THREAD

**Issue by Surpos0** [MoriyaShiine/bewitchment#333]
### Mod version

1.19-6

### A description of the issue

ghost spawned and i hitted him and then boom crash

### Log or crash report

https://gist.github.com/Surpos0/e3976230993e3ec717a8ba5fc09899a0

**Comment by Comdec35000** [comment]
My bad, you were on a multiplayer server, it's written in the crash report.
My guess was the issue come from package moriyashiine.bewitchment.common.entity.living.GhostEntity:141:21
the function isn't sided, so it runs client side, and so the ClientWorld can't be casted to ServerWorldAccess, and thus the client thread crashes
But I tested in solo and the call is only server side, so idk... Maybe the issue was fixed since
