### ISSUE TITLE
RItual of binding crashing server

### ISSUE THREAD

**Issue by nnssj** [MoriyaShiine/bewitchment#347]
### Mod version

v1.19-6

### A description of the issue

Trying to do a binding ritual for a raven, and upon doing it, the server crashes. It works in singleplayer.

### Log or crash report

https://gist.github.com/nnssj/c5a67aff423967d9461a58030d398ea2

**Comment by Comdec35000** [comment]
I'm unable to reproduce the issue on my game, but I belive it's caused by the game somehow struguling to save the raven, and then, when the ritual tries to save it to transfer the data to the familliar NBT (BindingFamilliarRitualFunction#start line 66) and then, when il tries to extract it to put in the familiar data (BindingFamiliarRitualFunction#start line 71) it gets a null and crashes.

I won't try a fix because I'm unable to check if my fix worked, but I think replacing `entityCompound.getUuid("UUID")` by `livingEntity.getUUID()` on line 75 may fix the problem
