### ISSUE TITLE
[1.19.2] Crash with eldritch mobs?

### ISSUE THREAD

**Issue by itsdinkd** [MoriyaShiine/bewitchment#359]
### Mod version

1.19-6

### A description of the issue

player visits a dimension, server stalls and crashes

### Log or crash report

https://gist.github.com/itsdinkd/80f1479657fe27f1a321ef91a74cd133

**Comment by MoriyaShiine** [comment]
Seems to be caused by Eldritch Mobs adding a new status effect every tick, so combined with Bewitchment checking nearby sigils for if the effect can be applied, the servers lags so much the process terminates.

This isn't something I'm really looking to fix due to the impending rewrite, but on their end they could instead add the status effect only if the entity doesn't already have it (and extend the duration)

**Comment by itsdinkd** [comment]
they fixed it on their end :) closing
