### ISSUE TITLE
OptiFabric non-compatibility, Our mod-pack no longer working without Bewitchment

### ISSUE THREAD

**Issue by trainheadcat** [MoriyaShiine/bewitchment#374]
### Mod version

1.20-4/Latest Version as of 8/3/23

### A description of the issue

When I launched Bewitchment with OptiFabric 1.13.25 it gives me an Incompatible mod set error, When we got this error we just deleted bewitchment which caused the entire mod-pack we created to not launch and gives us an exit code 1. When we readded Bewitchment and removed OptiFabric 1.13.25 the mod-pack started running again, and we would like this to be patched or added compatibility with OptiFabric 1.13.25 

### Log or crash report

https://gist.github.com/trainheadcat/1e5be6404268de27f772f639ef566a84

**Comment by Nidoskull** [comment]
OptiFabric breaks the majority of modpacks and compatibility is near-impossible due to the closed-source nature of OptiFabric. 
If you need performance boosting mods on Fabric, look into Sodium, Indium and Lithium
If you want shaders, look into Iris
If you want custom entity models, just google "CEM fabric" and you'll find a few ways it gets done
Anything OptiFabric does can be done by other mods too

**Comment by MoriyaShiine** [comment]
The message above explains it ^. Optifine causes random crashes with Bewitchment that I cannot fix, so I marked it as incompatible to avoid people reporting unfixable issues

**Comment by trainheadcat** [comment]
Thank you for the suggestion, I'll look into these fabric mods as I'm not familiar with fabric as I mainly used forge.
